version: '3.8'

services:
  qasa-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qasa-web-app
    ports:
      - "8080:8080"  # Web interface
      - "9000:9000"  # P2P network port
    volumes:
      # Persist QaSa configuration and keys
      - qasa-data:/home/qasa/.qasa
      # Optional: Mount SSL certificates if needed
      - ./ssl:/app/ssl:ro
    environment:
      - QASA_WEB_PORT=8080
      - QASA_NETWORK_PORT=9000
      - QASA_ENABLE_MDNS=true
      - QASA_ENABLE_DHT=true
    restart: unless-stopped
    networks:
      - qasa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Reverse proxy for production deployment
  nginx:
    image: nginx:alpine
    container_name: qasa-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - qasa-web
    restart: unless-stopped
    networks:
      - qasa-network
    profiles:
      - production

volumes:
  qasa-data:
    driver: local

networks:
  qasa-network:
    driver: bridge 